### ISSUE TITLE
Add jitter/noise to `shadow_shift` to seperate out repeats of the same value

### ISSUE THREAD

**Issue by tierneyn** [tierneyn/ggmissing#2]

**Comment by dicook** [comment]
done

need to add checks for variables types

**Comment by tierneyn** [comment]
Excellent, thank you!

I'll add "need to add checks for variables types" as an issue. I was thinking this could be done with S3 methods for each variable type - what do you think?

**Comment by dicook** [comment]
> On Dec 14, 2015, at 9:31 PM, Nicholas Tierney <notifications@github.com> wrote:
> 
> Excellent, thank you!
> 
> I'll add "need to add checks for variables types" as an issue. I was thinking this could be done with S3 methods for each variable type - what do you think?
> 

Yes, pbly - I’m not too good at error checking %^)

> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------
Di Cook
visnut@gmail.com
